### ISSUE TITLE
Ohne Funktion

### ISSUE THREAD

**Issue by thielen-t** [Bit-Line/microtools#3]
Ich bekomme dein Skript nicht zum laufen.

Nutze Synology Contacts.
Das Carddav File wird runter geladen.
Danach passiert aber nichts mehr.

**Comment by Bit-Line** [comment]
Also eigentlich sollte im gleichen Verzeichnis das "final.xml" durch Iterieren über die Kontakte gebaut werden, welches als remote File in Yealink-Telefonen geladen werden kann.
Auf welchem OS läuft das Script bei dir und kannst du bitte ein paar Echos als Debug-Hilfe rein bauen, um zu sehen, ob der Loop überhaupt startet?

Bei mir Läuft das auf einem ubuntu 16, getriggert durch php für manuellen Reload aus dem Browser und der www-root wird dann vom Telefon abgefragt.


php-script dazu: 
`<?php
      $message=shell_exec("/var/www/html/phonebook/builder.sh ; if [ $? -ne 1 ]; then echo 'Phonebook synced - OK!';fi ");
      print_r($message);
    ?>`

das final.xml sollte so aussehen:
`<YealinkIPPhoneDirectory>
<DirectoryEntry>
<Name>
First Name
 </Name>
<Telephone>
 012345678
</Telephone>
</DirectoryEntry>
<DirectoryEntry>
<Name>
Next Name
 </Name>
<Telephone>
 0123456789
</Telephone>
</DirectoryEntry>
</YealinkIPPhoneDirectory>`


Im Telefon konfigurierte URL:
http://10.9.2.15/phonebook/final.xml

**Comment by thielen-t** [comment]
Bei mir läuft es unter Ubuntu 20.04.
Habe es jetzt teilweise zum laufen bekommen.
Hatte Zeilenumbrüche in der XML Datei.

Jetzt habe ich nur noch Leerzeichen am Ende der Telefonnummer.

Mal sehen wie ich diese weg bekomme.

**Comment by Bit-Line** [comment]
sed -i -e '/^ */s///' -e '/ *$/s///' file.xml # remove leading blanks and trailing blanks

Quelle:
https://stackoverflow.com/questions/59715196/how-can-i-efficiently-remove-unnecessary-whitespace-from-xml-files-with-a-linux

**Comment by thielen-t** [comment]
Hatte ich gestern Abend auch schon gesehen.
Werde mich morgen daran setzen

**Comment by thielen-t** [comment]
Ich habe es hin bekommen.

ich habe am ende einfach 
sed -i.backup -re 's#[[:space:]]+##g;/^$/d' final.xml

somit werden alle Leerzeichen entfernt und das Telefonbuch funktioniert :-D
